FROM public.ecr.aws/lambda/python:3.13

COPY hair_classifier_empty.onnx.data .
COPY hair_classifier_empty.onnx .

FROM <https://habrastorage.org/webt/yf/_d/ok/yf_dokzqy3vcritme8ggnzqlvwa.jpeg>

RUN pip install --no-cache-dir numpy Pillow onnxruntime requests

COPY lambda_function.py lambda_function.py

CMD ["python", "lambda_function.py"]
